<?php

/**
 * @file
 * Contains cyberwoven_alert_bar.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cyberwoven_alert_bar_help($route_name, RouteMatchInterface $route_match) {
  $output = null;
  switch ($route_name) {
    // Main module help for the cyberwoven_alert_bar module.
    case 'help.page.cyberwoven_alert_bar':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Create and administer alerts for the site.') . '</p>';
    default:
  }
  return $output;
}

/**
 * Implements hook_theme().
 */
function cyberwoven_alert_bar_theme($existing, $type, $theme, $path) {

  return [
    'cyberwoven_alert_bar' => [
      'template' => 'cw-alert-bar',
      'variables' => [
        'attributes' => [],
        'enabled' => null,
        'expires' => null,
        'severity' => null,
        'message' => null,
        'more_link_label' => null,
        'more_link_url' => null,
        'more_link_external' => null,
        'alert_color_scheme' => null,
        'additional_classes' => null,
      ],
    ],
  ];

}

/**
 * Implements hook_preprocess_HOOK().
 */
function cyberwoven_alert_bar_preprocess_block__cyberwoven_alert_bar(&$variables) {
  $variables['#attached']['library'][] =  'cyberwoven_alert_bar/cyberwoven_alert_bar_functions';

  $config = \Drupal::config('cyberwoven_alert_bar.settings');

  // Get the UNIX timestamp of the expiration date,
  // and add one day to make it the last day the alert shows.
  $expires_date = date(strtotime($config->get('expires') . ' + 1 days'));

  $variables['#attached']['drupalSettings']['alertSettings'] = [
    'enabled' => $config->get('enabled'),
    'expires' => $expires_date,
    'severity' => $config->get('severity'),
    'message' => $config->get('message'),
    'more_link_label' => $config->get('more_link_label'),
    'more_link_url' => $config->get('more_link_url'),
    'more_link_external' => $config->get('more_link_external'),
    'alert_color_scheme' => $config->get('alert_color_scheme'),
    'additional_classes' => $config->get('additional_classes'),
  ];

}
