<?php

/**
 * @file
 * Contains cyberwoven_admin.module, for adding behavior and custom styles to the
 * Drupal admin theme (Seven).
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cyberwoven_admin_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cyberwoven_admin module.
    case 'help.page.cyberwoven_admin':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides admin tweaks Cyberwoven projects.') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_form_alter().
 */
function cyberwoven_admin_form_node_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{
  $form['#attached']['library'][] = 'cyberwoven_admin/global_styling';
  return $form;
}
